<%@ Page Title="" Language="C#" MasterPageFile="~/MainReg.Master" AutoEventWireup="true" CodeBehind="Cocina.aspx.cs" Inherits="Restaurant.Pages.Pantalla.Cocina" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Masterhead" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MasterContentPlaceHolder" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
    <ContentTemplate>

<div>
                <asp:GridView ID="GViewPedido" runat="server" CellPadding="4" 
                    ForeColor="#333333" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" onrowdeleting="GViewPedido_RowDeleting">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:BoundField DataField="id_pedido" HeaderText="id_pedido" Visible="false" />
                        <asp:BoundField DataField="id_suplementos" HeaderText="id_suplementos" Visible="false" />
                        <asp:BoundField DataField="id_horario" HeaderText="id_horario" Visible="false" />
                        <asp:BoundField DataField="id_mesas" HeaderText="Mesa" />
                        <asp:BoundField DataField="pedido_silla" HeaderText="Silla" />
                        <asp:BoundField DataField="id_platillos" HeaderText="id_platillos" Visible="false" />
                        <asp:BoundField DataField="platillos_nombre" HeaderText="Platillo" />
                        <asp:BoundField DataField="suplementos_nombre" HeaderText="Suplemento" />
                    </Columns>
                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>

 <asp:Button ID="BtnActualizar" runat="server" Text="Actualizar" 
                    CssClass="btn btn-primary" onclick="BtnActualizar_Click" />
</div>
    </ContentTemplate>
     <Triggers>
    <asp:AsyncPostBackTrigger ControlID="Timer1" EventName="Tick" /> 
  </Triggers> 
</asp:UpdatePanel>

<asp:Timer runat="server" id="Timer1" Enabled="true" 
  Interval="60000" OnTick="Timer1_Tick" />


</asp:Content>
